# Generated by Django 5.2.17 on 2026-10-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "lands",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Districts"
                    ),
                ),
                ("month", models.CharField(blank=True, max_length=40)),
                ("nights", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("travellers", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("budget", models.CharField(blank=True, max_length=60)),
                ("message", models.TextField(blank=True)),
                (
                    "contact_pref",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("call", "Phone call"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                        verbose_name="Best way to reach you",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("full", "Full form"),
                            ("quick", "Quick form"),
                            ("callback", "Call back"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                ("source_page", models.CharField(blank=True, max_length=300)),
                ("handled", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "enquiries",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("source_page", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
